### ISSUE TITLE
DrXama_updateManager Incompatibilidade com Victor Engine

### ISSUE THREAD

**Issue by phyluna** [GS-GAME-WORDS/Dr.Xama---RPG-MAKER-MV#2]
Por alguma razão após atualizar o jogo os scripts do Victor Engine são "desativados", existe alguma maneira de fazer os dois funcionarem juntos?

**Comment by DrXama** [comment]
Estou retornando as atividades, desculpe pela demora. Não tenho prazo de solução definido no momento, peço que aguarde.

**Comment by phyluna** [comment]
Muito obrigada, vou ficar no aguardo da correção de compatibilidade

**Comment by DrXama** [comment]
Por gentileza me passa a lista dos plugins do Victor que você tentou usar junto com o plugin "DrXama_updateManager"

**Comment by phyluna** [comment]
Esses são os plug-ins que utilizo, vou colocar na ordem de ativação que utilizo no meu projeto:

Basic Module
https://victorenginescripts.wordpress.com/rpg-maker-mv/basic-module/

Damage Popup
https://victorenginescripts.wordpress.com/rpg-maker-mv/damage-popup/

Battle Motions
https://victorenginescripts.wordpress.com/rpg-maker-mv/battle-motions/

Battler Graphic Setup
https://victorenginescripts.wordpress.com/rpg-maker-mv/battler-graphic-setup/

Passive States
https://victorenginescripts.wordpress.com/rpg-maker-mv/passive-states/

Active Time Battle
https://victorenginescripts.wordpress.com/rpg-maker-mv/active-time-battle/

**Comment by DrXama** [comment]
Problema Corrigido! 
[commit ](https://github.com/GS-GAME-WORDS/Dr.Xama---RPG-MAKER-MV/commit/c1a5d19a41e21a7247acad1b64b01b25c918ea8c)
